version: "3.9"

services:
  backend:
    image: ${BACKEND_IMAGE:-impulsyia/backend:latest}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env

  frontend:
    image: ${FRONTEND_IMAGE:-impulsyia/frontend:latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
